version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "type/update"
